/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import com.componentfolders.Model.Chip;
import com.componentfolders.Service.ITF.ChipService;
import com.componentfolders.Service.Impl.ChipServiceImpl;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BuiDucMinh
 */
public class FromChip extends javax.swing.JFrame {

    /**
     * Creates new form FromChip
     */
    private ChipService chipService;
    private DefaultTableModel tableModel;
    private ArrayList<Chip> list;

    public FromChip() {
        initComponents();
        setLocationRelativeTo(null);
        chipService = new ChipServiceImpl();
        loadData(list);
    }

    private void loadData(ArrayList<Chip> list) {
        tableModel = (DefaultTableModel) tbchip.getModel();
        tableModel.setRowCount(0);
        for (Chip chip : chipService.getAllChip()) {
            tableModel.addRow(new Object[]{
                chip.getId(), chip.getMaChip(), chip.getTenChip()
            });
        }
    }

    private void mouseClick() {
        int index = tbchip.getSelectedRow();
        lblidchip.setText(tbchip.getValueAt(index, 0).toString());
        txtmachip.setText(tbchip.getValueAt(index, 1).toString());
        txttenchip.setText(tbchip.getValueAt(index, 2).toString());
    }

    private boolean validateFrom(String check) {
        if (txtmachip.getText().isEmpty() || txttenchip.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thong Tin Khong Duoc De Trong");
            return false;
        }
        return true;
    }

    private Chip addFrom() {
        Chip chip = new Chip();
        chip.setMaChip(txtmachip.getText().trim());
        chip.setTenChip(txttenchip.getText().trim());
        return chip;
    }

    private Chip updateFrom() {
        Chip chip = new Chip();
        chip.setId(Integer.parseInt(lblidchip.getText().trim()));
        chip.setMaChip(txtmachip.getText().trim());
        chip.setTenChip(txttenchip.getText().trim());
        return chip;
    }

    private void addRow() {
        if (chipService.checkTrung(txtmachip.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Ma Trung");
            return;
        }
        if (!validateFrom("add row")) {
            return;
        }
        String add = chipService.addChip(addFrom());
        list = (ArrayList<Chip>) chipService.getAllChip();
        loadData(list);
        JOptionPane.showMessageDialog(this, add);
    }

    private void updateRow() {
        int index = tbchip.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Chon Dong De Sua");
        } else {
            if (!validateFrom("update")) {
                return;
            }
            String update = chipService.updateChip(updateFrom());
            list = (ArrayList<Chip>) chipService.getAllChip();
            loadData(list);
            JOptionPane.showMessageDialog(this, update);
        }
    }

    private void deleteRow() {
        int index = tbchip.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Chon Dong De Xoa");
        } else {
            int luaChon = JOptionPane.showConfirmDialog(this, "Ban Co Chac Chan Muon Xoa Khong", "Thong Bao", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (luaChon == JOptionPane.YES_OPTION) {
                String delete = chipService.deleteChip(Integer.parseInt(lblidchip.getText().trim()));
                list = (ArrayList<Chip>) chipService.getAllChip();
                loadData(list);
                JOptionPane.showMessageDialog(this, delete);
            } else {

            }
        }
    }

    private void newFrom() {
        lblidchip.setText("");
        txtmachip.setText("");
        txttenchip.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmachip = new javax.swing.JTextField();
        txttenchip = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbchip = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblidchip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("THUOC TINH CHIP");

        jLabel2.setText("Ma Chip:");

        jLabel3.setText("Ten Chip:");

        btnadd.setText("THEM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("CAP NHAT");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("XOA");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnresert.setText("LAM MOI");
        btnresert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresertActionPerformed(evt);
            }
        });

        tbchip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MA CHIP", "TEN CHIP"
            }
        ));
        tbchip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbchipMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbchip);

        jLabel4.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnresert))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmachip)
                                    .addComponent(txttenchip, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblidchip, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(lblidchip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmachip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenchip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnresert))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        addRow();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        updateRow();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        deleteRow();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresertActionPerformed
        // TODO add your handling code here:
        newFrom();
    }//GEN-LAST:event_btnresertActionPerformed

    private void tbchipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbchipMouseClicked
        // TODO add your handling code here:
        mouseClick();
    }//GEN-LAST:event_tbchipMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromChip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromChip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromChip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromChip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromChip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnresert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblidchip;
    private javax.swing.JTable tbchip;
    private javax.swing.JTextField txtmachip;
    private javax.swing.JTextField txttenchip;
    // End of variables declaration//GEN-END:variables
}
