/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import com.componentfolders.Model.Pin;
import com.componentfolders.Service.ITF.PinService;
import com.componentfolders.Service.Impl.PinServiceImpl;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BuiDucMinh
 */
public class PinFrom extends javax.swing.JFrame {

    /**
     * Creates new form PinFrom
     */
    private PinService pinService;
    private DefaultTableModel tableModel;
    private ArrayList<Pin> list;
    
    public PinFrom() {
        initComponents();
        setLocationRelativeTo(null);
        pinService = new PinServiceImpl();
        loadData(list);
    }

    private void loadData(ArrayList<Pin> list1){
        tableModel = (DefaultTableModel) tbpin.getModel();
        tableModel.setRowCount(0);
        for(Pin pin : pinService.getAllPin()){
            tableModel.addRow(new Object[]{
                pin.getId(), pin.getMaPin(), pin.getTenPin()
            });
        }
    }
    
    private void mouseClick(){
        int index = tbpin.getSelectedRow();
        lblidpin.setText(tbpin.getValueAt(index, 0).toString());
        txtmapin.setText(tbpin.getValueAt(index, 1).toString());
        txttenpin.setText(tbpin.getValueAt(index, 2).toString());
    }
    
    private boolean validateFrom(String check){
        if(txtmapin.getText().isEmpty() || txttenpin.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Thong Tin Khong Duoc De Trong");
            return false;
        }
        return true;
    }
    
    private Pin addFrom(){
        Pin pin = new Pin();
        pin.setMaPin(txtmapin.getText().trim());
        pin.setTenPin(txttenpin.getText().trim());
        return pin;
    }
    
    private Pin updateFrom(){
        Pin pin = new Pin();
        pin.setId(Integer.parseInt(lblidpin.getText().trim()));
        pin.setMaPin(txtmapin.getText().trim());
        pin.setTenPin(txttenpin.getText().trim());
        return pin;
    }
    
    private void addRow(){
        if(pinService.checkTrung(txtmapin.getText().trim())){
            JOptionPane.showMessageDialog(this, "Ma Trung");
            return;
        }
        if(!validateFrom("add row")){
            return;
        }
        String add = pinService.addPin(addFrom());
        list = (ArrayList<Pin>) pinService.getAllPin();
        loadData(list);
        JOptionPane.showMessageDialog(this, add);
    }
    
    private void updateRow(){
        int index = tbpin.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Chon Dong De Sua");
        }else{
            if(!validateFrom("update")){
                return;
            }
            String update = pinService.updatePin(updateFrom());
            list = (ArrayList<Pin>) pinService.getAllPin();
            loadData(list);
            JOptionPane.showMessageDialog(this, update);
        }
    }
    
    private void deleteRow(){
        int index = tbpin.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Chon Dong De Xoa");
        }else{
            int luaChon = JOptionPane.showConfirmDialog(this, "Ban Co Chac Chan Muon Xoa Khong", "Thong Bao", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(luaChon == JOptionPane.YES_OPTION){
                String delete = pinService.deletePin(Integer.parseInt(lblidpin.getText().trim()));
                list = (ArrayList<Pin>) pinService.getAllPin();
                loadData(list);
                JOptionPane.showMessageDialog(this, delete);
            }else{
                
            }
        }
    }
    
    private void newFrom(){
        lblidpin.setText("");
        txtmapin.setText("");
        txttenpin.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmapin = new javax.swing.JTextField();
        txttenpin = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblidpin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("THUOC TINH PIN");

        jLabel2.setText("Ma Pin:");

        jLabel3.setText("Ten Pin:");

        btnadd.setText("THEM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("CAP NHAT");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("XOA");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnresert.setText("LAM MOI");
        btnresert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresertActionPerformed(evt);
            }
        });

        tbpin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MA PIN", "TEN PIN"
            }
        ));
        tbpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpin);

        jLabel4.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmapin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnadd)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnupdate)
                                                .addGap(18, 18, 18)
                                                .addComponent(btndelete)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnresert))
                                            .addComponent(txttenpin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblidpin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(lblidpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmapin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttenpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnresert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        addRow();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        updateRow();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        deleteRow();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresertActionPerformed
        // TODO add your handling code here:
        newFrom();
    }//GEN-LAST:event_btnresertActionPerformed

    private void tbpinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpinMouseClicked
        // TODO add your handling code here:
        mouseClick();
    }//GEN-LAST:event_tbpinMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnresert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblidpin;
    private javax.swing.JTable tbpin;
    private javax.swing.JTextField txtmapin;
    private javax.swing.JTextField txttenpin;
    // End of variables declaration//GEN-END:variables
}
