/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import com.componentfolders.Model.Ram;
import com.componentfolders.Service.ITF.RamService;
import com.componentfolders.Service.Impl.RamServiceImpl;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BuiDucMinh
 */
public class RamFrom extends javax.swing.JFrame {

    /**
     * Creates new form RamFrom
     */
    private RamService ramService;
    private DefaultTableModel tableModel;
    private ArrayList<Ram> list;

    public RamFrom() {
        initComponents();
        setLocationRelativeTo(null);
        ramService = new RamServiceImpl();
        loadData(list);
    }

    private void loadData(ArrayList<Ram> list) {
        tableModel = (DefaultTableModel) tbram.getModel();
        tableModel.setRowCount(0);
        for (Ram ram : ramService.getAllRam()) {
            tableModel.addRow(new Object[]{
                ram.getId(), ram.getMaRam(), ram.getDungLuong()
            });
        }
    }

    private void mouseClick() {
        int index = tbram.getSelectedRow();
        lblidram.setText(tbram.getValueAt(index, 0).toString());
        txtmaram.setText(tbram.getValueAt(index, 1).toString());
        txtdungluongram.setText(tbram.getValueAt(index, 2).toString());
    }

    private boolean validateFrom(String check) {
        if (txtmaram.getText().isEmpty() || txtdungluongram.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thong Tin Khong Duoc De Trong");
            return false;
        }
        try {
            int dungLuongRom = Integer.parseInt(txtdungluongram.getText());
            if (dungLuongRom < 0) {
                JOptionPane.showMessageDialog(this, "Ram Khong Ton Tai");
                return false;
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dung Luong Phai La So");
            return false;
        }
        return true;
    }

    private Ram addFrom() {
        Ram ram = new Ram();
        ram.setMaRam(txtmaram.getText().trim());
        ram.setDungLuong(Integer.parseInt(txtdungluongram.getText().trim()));
        return ram;
    }

    private Ram updateFrom() {
        Ram ram = new Ram();
        ram.setId(Integer.parseInt(lblidram.getText().trim()));
        ram.setMaRam(txtmaram.getText().trim());
        ram.setDungLuong(Integer.parseInt(txtdungluongram.getText().trim()));
        return ram;
    }

    private void addrow() {
        if (ramService.checkTrung(txtmaram.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Ma Trung");
            return;
        }
        if (!validateFrom("Add ram")) {
            return;
        }
        String add = ramService.addRam(addFrom());
        list = (ArrayList<Ram>) ramService.getAllRam();
        loadData(list);
        JOptionPane.showMessageDialog(this, add);
    }

    private void updateRow() {
        int index = tbram.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Chon Dong De Sua");
        } else {
            if (!validateFrom("update ram")) {
                return;
            }
            String update = ramService.updateRam(updateFrom());
            list = (ArrayList<Ram>) ramService.getAllRam();
            loadData(list);
            JOptionPane.showMessageDialog(this, update);
        }
    }

    private void deleteRow() {
        int index = tbram.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Chon Dong De Xoa");
        } else {
            int luaChon = JOptionPane.showConfirmDialog(this, "Ban Co Chac Chan Muon Xoa Khong", "Thong Bao", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (luaChon == JOptionPane.YES_OPTION) {
                String delete = ramService.deleteRam(Integer.parseInt(lblidram.getText().trim()));
                list = (ArrayList<Ram>) ramService.getAllRam();
                loadData(list);
                JOptionPane.showMessageDialog(this, delete);
            } else {
            }
        }
    }

    private void newFrom() {
        lblidram.setText("");
        txtmaram.setText("");
        txtdungluongram.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmaram = new javax.swing.JTextField();
        txtdungluongram = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbram = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblidram = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("THUOC TINH RAM");

        jLabel2.setText("Ma Ram:");

        jLabel3.setText("Dung Luong:");

        btnadd.setText("THEM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("CAP NHAT");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("XOA");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnresert.setText("LAM MOI");
        btnresert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresertActionPerformed(evt);
            }
        });

        tbram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MA RAM", "DUNG LUONG"
            }
        ));
        tbram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbramMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbram);

        jLabel4.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnadd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnupdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnresert))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtdungluongram, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtmaram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblidram, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(lblidram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdungluongram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnresert))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        addrow();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        updateRow();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        deleteRow();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresertActionPerformed
        // TODO add your handling code here:
        newFrom();
    }//GEN-LAST:event_btnresertActionPerformed

    private void tbramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbramMouseClicked
        // TODO add your handling code here:
        mouseClick();
    }//GEN-LAST:event_tbramMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnresert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblidram;
    private javax.swing.JTable tbram;
    private javax.swing.JTextField txtdungluongram;
    private javax.swing.JTextField txtmaram;
    // End of variables declaration//GEN-END:variables

}
